---
language: node_js
node_js:
- "0.12"
env:
  global:
    CONTENT_STORE_URL: https://deconst.horse:9000/
    NODE_TLS_REJECT_UNAUTHORIZED: 0
install:
- npm install -g grunt-cli
- npm install
script:
- grunt
